### ISSUE TITLE
When try to check whether user had login to the system when website load State updates infinitely 

### ISSUE THREAD

**Issue by NipunaMarcus** [asgardeo/asgardeo-auth-react-sdk#121]
**Describe the issue:**
When trying to check whether the user had a login to the system when the website State updates infinitely till we get a response back as far as I understood.

Code sample: 
    https://github.com/LSFLK/MedicinesforLK/blob/development/admin-portal/src/App.tsx#L26

This happens when we have selected workers as our storage option. This works fine for other two storage options (localstorage, session storage)

**How to reproduce:**
  -  https://github.com/LSFLK/MedicinesforLK/blob/development/admin-portal/src/App.tsx#L26
  - Do something similar to the above code while have set the storage option to worker.

**Expected behavior:**
If the user logged in update the state to have authenticated true and loading false.
If the user is not logged in redirect the user to the login page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Latest
 - OS: Mac

**Comment by yathindrakodithuwakku** [comment]
The issue reproduced with [create-react-app](https://create-react-app.dev/) even without using silent auth check. 

https://user-images.githubusercontent.com/32919513/185151655-9df2e5ed-20d2-45f1-908c-29f139b1e875.mp4

**Comment by pavinduLakshan** [comment]
Closing this issue based on https://github.com/LSFLK/MedicinesforLK/pull/430
