### ISSUE TITLE
[REACT 18] Race condition in applications when `Strict Mode` is turned on.

### ISSUE THREAD

**Issue by brionmario** [asgardeo/asgardeo-auth-react-sdk#125]
**Describe the issue:**

When `@asgardeo/auth-react` is used in a React 18 application with strict mode, it goes in to an infinite loop.

![loop](https://user-images.githubusercontent.com/25959096/185784171-fb582e00-9032-489d-aec9-07f7495a8044.gif)
 

**How to reproduce:**
1. Create a react app with [CRA](https://reactjs.org/docs/create-a-new-react-app.html)
2. Integrate Asgardeo Auth React. (Guide https://wso2.com/asgardeo/docs/get-started/try-your-own-app/react/#prerequisites)

**Expected behavior:**
The application shouldn't loop.

**Additional Context:**
This seems to happening due to the [ensuring-reusable-state](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state) feature in Strict Mode in React 18.

The use effect inside `Auth Provider` is called twice causing a race condition. (https://github.com/asgardeo/asgardeo-auth-react-sdk/blob/v1.1.15/lib/src/authenticate.tsx#L149)

**Comment by yathindrakodithuwakku** [comment]
Fixes https://github.com/asgardeo/asgardeo-auth-react-sdk/pull/128
