### ISSUE TITLE
`isAuthenticated` Returns false even when Signed In Already

### ISSUE THREAD

**Issue by chaminjay** [asgardeo/asgardeo-auth-react-sdk#143]
**Describe the issue:**
`state.isAuthenticated` returns false even after signed into the application successfully. It returns true only if `signIn()` method invoked manually. i.e. clicking the "Login" button again

**How to reproduce:**
1. Setup a ReactJs SPA with Asgardeo configs
2. Sign into the app
3. Observe the value of `isAuthenticated`

**Expected behavior:**
`isAuthenticated` should return `true` if the user has successfully signed in.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Node Version: 14.20.0
 - OS: macOs
 - npm Version: 6.14.17

**Comment by yathindrakodithuwakku** [comment]
Got the same issue when the apps get the authorization code and session state. At this point, if we check the`isAuthenticated` flag, we get false, which is incorrect. This caused an endless loop, as the sdk continuously tries to get the user authenticated.

App type: `Create React App`
Node Version: 16.15.0
OS: macOS
pnpm Version: 7.11.0
