### ISSUE TITLE
Add support for Node 17+ versions

### ISSUE THREAD

**Issue by kavinda1995** [asgardeo/asgardeo-auth-react-sdk#146]
**Describe the issue:**
We are getting the following error when we try to start our react sample in `Node 17+` versions and the newest LTS `18.12.0`. 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/19621533/198042552-6cc49d26-83be-4199-83ad-2f5ef37640d9.png">

The major reason is that in node 17, they've changed the implementation of SSL handling, which came as a breaking change for older code bases [[1]](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/73027407#73027407). We might need to bump our packages accordingly or configure webpack to support this.

**How to reproduce:**
1. Install or switch to Node >17
2. Try to start the sample app
3. You'll see an error mentioned above

**Expected behavior:**
Sample app should start without any issues

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - OS: [e.g., Windows, Linux, Mac] - Mac
 - Node - >17

---

### Optional Fields
* Ref - https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/73027407#73027407

**Comment by DonOmalVindula** [comment]
`v2.0.0` of the `asgardeo-auth-react-sdk`  have added support up to node 18 (latest). Therefore closing this issue.
