### ISSUE TITLE
Allow the sign-in redirect to go back to the page the sign-in was initiated from

### ISSUE THREAD

**Issue by dinuka-rp** [asgardeo/asgardeo-auth-react-sdk#149]
**Describe the issue:**

Currently, the Redirect URL is static. The URL can't be changed to dynamically set the redirect URL. This means that it would always take the user back to the home page after a successful login, even if the user triggers the Asgardeo sign-in from a sub-route.

**How to reproduce:**
1. In an app that has Asgardeo sign-in integrated, click-on sign-in inside a sub-route.
2. Complete the sign-in process
_Asgardeo will redirect the user to the home page (the pre-set redirect URL)_

**Expected behavior:**
Redirect the user to the URL that the user clicked on the sign-in button.

**Suggestion:**
The SDK could save this redirect URL in session storage. In the SDK, when attempting to redirect, if there is a redirect URL saved in session storage, that could be used. If not, the Redirect URL that was set from the deployment env variables can be used.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 1.1.18
 
---

### Optional Fields

**Related issues:**

https://github.com/LSFLK/MedicinesforLK/issues/527

@nipunsampath @anjula-sack

**Comment by pavinduLakshan** [comment]
> The SDK could save this redirect URL in session storage. In the SDK, when attempting to redirect, if there is a redirect URL saved in session storage, that could be used. If not, the Redirect URL that was set from the deployment env variables can be used.

This is out of the scope of this SDK. The primary purpose of this SDK is to handle the authentication process and manage the credentials.

As a solution to your requirement, you may implement the above quoted logic in your own page, and set the link to that page as the redirect URI in your Asgardeo application. Then, once Asgardeo redirects the user to that specific page, you can redirect the user from there to where the user started the sign in process.
