### ISSUE TITLE
`react-router-dom` dependency needs to be updated

### ISSUE THREAD

**Issue by SkNuwanTissera** [asgardeo/asgardeo-auth-react-sdk#151]
**Describe the issue:**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: medi-agency-ca@0.1.0
npm ERR! Found: react-router-dom@6.4.3
npm ERR! node_modules/react-router-dom
npm ERR!   react-router-dom@"^6.4.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-router-dom@"^5.2.0" from @asgardeo/auth-react@1.1.18
npm ERR! node_modules/@asgardeo/auth-react
npm ERR!   @asgardeo/auth-react@"^1.1.18" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/nuwantissera/.npm/_logs/2022-11-19T16_29_00_480Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nuwantissera/.npm/_logs/2022-11-19T16_29_00_480Z-debug-0.log

**How to reproduce:**

Try to `npm install` and start this project https://github.com/indikasampath2000/cnappdev-e2e-usecase-react-app/pull/1/files

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Related https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/137

**Comment by DonOmalVindula** [comment]
`v2.0.0` of `asgardeo-auth-react-sdk` have added support for node 18 and `react-router-dom` v6. Therefore closing this issue
