### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [asgardeo/asgardeo-auth-react-sdk#189]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by pavinduLakshan** [comment]
Hi @igibek ,

Thank you for taking the time to notify us of the vulnerability you have discovered and for bringing to our attention the "Private vulnerability reporting" feature. Your report has been duly noted, and I will ensure that the relevant team is informed.

In the meantime, we encourage you to follow the steps outlined in our [security policy](https://github.com/asgardeo/asgardeo-auth-react-sdk/security/policy) to report any vulnerabilities you may discover. Thank you again for your cooperation in helping us maintain a secure platform.
