### ISSUE TITLE
Issuer Claim Validation Error when not starting IS on default port

### ISSUE THREAD

**Issue by viggnah** [asgardeo/asgardeo-auth-react-sdk#196]
**Describe the issue:**
I started WSO2 IS on port 9500 and followed the instructions on [this](https://is.docs.wso2.com/en/6.0.0/sdks/start-integrating-apps/integrate-a-react-app/) page. I replaced `"baseUrl": "https://localhost:9443"` with `"baseUrl": "https://localhost:9500"` and I got redirected to the Issuer Claim Validation Error page on login.

Note: When I start on 9443 I am able to login properly.

**How to reproduce:**
1. Open the deployment.toml file found in the <IS-Home>/repository/conf/ directory, and add the following configuration:
```
[server]
offset = 57
```
2. Follow the rest of the steps as per [this](https://is.docs.wso2.com/en/6.0.0/sdks/start-integrating-apps/integrate-a-react-app/) doc
3. But replace `"baseUrl": "https://localhost:9443"` with `"baseUrl": "https://localhost:9500"` 

**Expected behavior:**
Successful login

**Environment information:**
 - Product Version: IS 6.0.0
 - OS:  Mac
 - Database: H2 (Default)
 - Userstore: Default

**Comment by shaouari** [comment]
in Identity Providers -> resident -> Inbound Authentication Configuration-> OAuth2/OpenID Connect Configuration

update the Identity Provider Entity ID value to match your baseurl + /oauth2/token

**Comment by pavinduLakshan** [comment]
> in Identity Providers -> resident -> Inbound Authentication Configuration-> OAuth2/OpenID Connect Configuration
> 
> update the Identity Provider Entity ID value to match your baseurl + /oauth2/token

Thanks for posting the solution @shaouari. We will get this added to the [docs](https://is.docs.wso2.com/en/6.0.0/sdks/start-integrating-apps/integrate-a-react-app/)
