### ISSUE TITLE
Provide pre-defined profile management, login, logout buttons using React components

### ISSUE THREAD

**Issue by wx-yz** [asgardeo/asgardeo-auth-react-sdk#197]
**Is your feature request related to a problem? Please describe.**
It's a common enough requirement that when you add authentication to a React app, the next thing you want to do is provide login/logout and profile management features.  Right now we're leaving this to the user to implement and provide that capability in the webapps they write.

**Describe the solution you would prefer**
IMO to get to a state where Asgardeo React SDK is the preferred SDK developers think about when they want to enable authentication and profile management features, we should provide these as pre-defined React components. So the developer experience is you just install the SDK and can include something like <MyProfile />. 

My idea is that this button will render a profile icon and when it's clicked on, you can do sign out, change profile attributes, enroll MFA keys etc... all through that pop-up without ever having to leave the app OR going to Asgardeo console.

**Comment by pavinduLakshan** [comment]
Hi Chintana,

This improvement is currently being worked on. The plan is to introduce a separate SDK with utility methods and customizable UI components that can be used to build custom and dynamic authentication/user mgt experiences.

You can view the current progress from the referenced IAM project tracking issue above.
