### ISSUE TITLE
Source code should not be packed into the NPM package

### ISSUE THREAD

**Issue by pavinduLakshan** [asgardeo/asgardeo-auth-react-sdk#200]
**Is your suggestion related to an experience ? Please describe.**

The bundled package in the NPM registry contains the uncompiled src directory as well in it, accounting for about 45KB/700KB, even though it brings no value to the end users.

![image](https://github.com/asgardeo/asgardeo-auth-react-sdk/assets/41533942/5b38b32e-3c3e-44d1-9448-808d25078ef9)

In addition, the compiled types need to be in the dist directory itself or in a meaningful folder structure (eg: `dist/types`)

![Screenshot 2023-08-07 at 21 44 25](https://github.com/asgardeo/asgardeo-auth-react-sdk/assets/41533942/47b050a0-b2a2-445b-b2c7-9d474b18e817)

**Describe the improvement**

src/ folder shouldn't be packed into the NPM package.

**Additional context**

N/A

**Comment by s-vamshi** [comment]
Hey @NipuniBhagya @pavinduLakshan I would like to work on this issue, can you please assign this to me?

**Comment by pavinduLakshan** [comment]
> Hey @NipuniBhagya @pavinduLakshan I would like to work on this issue, can you please assign this to me?

Hi @s-vamshi, done. If you have anything to clarify, please feel free to get back.

**Comment by s-vamshi** [comment]
hey @pavinduLakshan, if I am not wrong I need to exclude src from auth-react package right? not in this repo right? please guide me.

**Comment by s-vamshi** [comment]
one of the example uses auth-react package

**Comment by s-vamshi** [comment]
Hey @pavinduLakshan I have open PR, can you please review this PR in your free time?
