### ISSUE TITLE
Unable to use RefreshAccesToken() to get a new access token after the current one expires

### ISSUE THREAD

**Issue by nisuraaa** [asgardeo/asgardeo-auth-react-sdk#225]
Trying to invoke the RefreshAccessToken() manually after the access token expires gives me the following error on the browser console

<img width="571" alt="image" src="https://github.com/asgardeo/asgardeo-auth-react-sdk/assets/64645496/1fe92d19-0006-4968-92bb-95a002b33317">

However attempting use the get a new token by sending the same refresh token via an API call (via Postman) to the Asgardeo Server is successful

Is this by design?

**Comment by DucTuanmdt** [comment]
I encountered the same issue. Upon investigating the [asgardeo-auth-spa-sdk](https://github.com/asgardeo/asgardeo-auth-spa-sdk), I noticed that before`refreshAccessToken` is called, there is a check for authentication at the following locations:

[refreshAccessToken()](https://github.com/asgardeo/asgardeo-auth-spa-sdk/blob/main/lib/src/client.ts#L919
)
```
public async refreshAccessToken(): Promise<BasicUserInfo | undefined> {
    await this._validateMethod();

    return this._client?.refreshAccessToken();
}
```

[_validateMethod()](https://github.com/asgardeo/asgardeo-auth-spa-sdk/blob/main/lib/src/client.ts#L157)
```
if (validateAuthentication && !(await this.isAuthenticated())) {
    return Promise.reject(
        new AsgardeoAuthException(
            "SPA-AUTH_CLIENT-VM-IV02",
            "The user is not authenticated.",
            "The user must be authenticated first."
        )
    );
}
```
I believe it would be beneficial to have an option to bypass this check when attempting to refresh an expired access token.

**Comment by davidtranjs** [comment]
+1 same issue here
What is the point of check access token expired before excute refresh token ?

**Comment by nisuraaa** [comment]
A workaround would be to downgrade the SDK version to 3.0.2

**Comment by davidtranjs** [comment]
@nisuraaa downgrade an major version can lead to a lot of other issues too 😢

**Comment by pavinduLakshan** [comment]
Hi @nisuraaa and @davidtranjs, I too believe that it doesn't make sense to have `isAuthenticated` check before refreshing the access token. 

@brionmario thoughts?

**Comment by brionmario** [comment]
+1 to remove the check.
With https://github.com/asgardeo/asgardeo-auth-js-core/pull/242, we are now checking the `expiry` time. Hence, it'll fail when the time is exceeded.

**Comment by pavinduLakshan** [comment]
> +1 to remove the check. With [asgardeo/asgardeo-auth-js-core#242](https://github.com/asgardeo/asgardeo-auth-js-core/pull/242), we are now checking the `expiry` time. Hence, it'll fail when the time is exceeded.

Ack. will send a fix.
