### ISSUE TITLE
Could not initiate token request when configuring wellknown endpoint for an external identity provider

### ISSUE THREAD

**Issue by piraveena** [asgardeo/asgardeo-auth-react-sdk#30]
**Describe the issue:**
```
const App = () => (
    <AuthProvider
        config={ {
          signInRedirectURL: "http://localhost:3000",
          signOutRedirectURL: "http://localhost:3000/",
            clientID: "qxVkdTUc50leBKZFj1HnEOGOMbhEtzqx",
            serverOrigin: "https://<idp_domain_name>",
            wellKnownEndpoint: "/.well-known/openid-configuration",
        } }
    >
      { /* Use your own component tree here instead of HomePage.  */ }
      <LandingPage />
    </AuthProvider>
);
```

Similar to this https://github.com/asgardeo/asgardeo-auth-angular-sdk/issues/80

Authorization code flow is working as expected. But token flow is not working. there is call to token endpoint in the network trace as well.

AuthorizationRequest:
`https://<idp_issuer_value>/authorize?response_type=code&client_id=<clientId>&scope=openid&redirect_uri=https%3A%2F%2Flocalhost%3A3000&response_mode=query&code_challenge_method=S256&code_challenge=-BAT5kFeMw6Mx9ZLZQf5xaW7W320eaiJqWbFJJHm9L0`

Response:
`https://localhost:3000/?code=5LjrbgCq8rce41wg`

**Comment by piraveena** [comment]
The root cause for this issue is, SDK depends on the session_state param to initiate the token request.

**Comment by thivi** [comment]
Resolved by https://github.com/asgardeo/asgardeo-auth-js-sdk/issues/35 and https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/36
