### ISSUE TITLE
Can't create two auth client instances

### ISSUE THREAD

**Issue by chathuranga95** [asgardeo/asgardeo-auth-react-sdk#41]
**Describe the issue:**
The `getInstance` [API](https://github.com/asgardeo/asgardeo-auth-spa-sdk#getinstance) doesn't create multiple instances.

**How to reproduce:**
```
const authClient = AsgardeoSPAClient.getInstance();
const fooAuthClient = AsgardeoSPAClient.getInstance("foo");
// initialize both clients (set configs to use session storage)
// sign in to both clients
```
on session storage, only one auth client instance can be seen.

**Expected behavior:**
Both auth client instances should be available on the stoarage (in this case, the session storage)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: react sdk 1.0.4
 - OS:  ubutnu 20.02
 - Browser: chrome

**Comment by brionmario** [comment]
Are you trying to create multiple instances in React SDK or SPA SDK?
