### ISSUE TITLE
Need a new API to sign in with a custom grant

### ISSUE THREAD

**Issue by chathuranga95** [asgardeo/asgardeo-auth-react-sdk#42]
**Is your feature request related to a problem? Please describe.**
When Choreo apim devportal's custom grant request is enabled, it is unable to perform a token refresh. Therefore, a new API is needed to store the token obtained from the orginal idp (choreo idp), use it to exchange the token (custom grant request) and use it to refresh the token.

Use case, current implementation, issues in current implementation and details on the suggested API are documented in [[1]](https://docs.google.com/document/d/1h9s2ox0IFfyvlENEoBCc_8V5tXldC7bqYmD7LrtlsZA/edit?usp=sharing)

**Describe the solution you would prefer**
A new API is needed to solve the shortcomings of using the current APIs in sdk. details are documented in [[1]](https://docs.google.com/document/d/1h9s2ox0IFfyvlENEoBCc_8V5tXldC7bqYmD7LrtlsZA/edit?usp=sharing).

**Comment by pavinduLakshan** [comment]
`requestCustomGrant` function is now accessible through the [SPA SDK](https://github.com/wso2-enterprise/asgardeo-auth-spa-sdk).
