### ISSUE TITLE
Automatically get redirected to login page of IdP when upon application refresh

### ISSUE THREAD

**Issue by ayshsandu** [asgardeo/asgardeo-auth-react-sdk#52]
I have integrated `@asgardeo/auth-react": "0.2.4` to my react application and created a login button on the landing page.

```<button onClick={() => signIn()}>Login</button>```

When I keep refreshing the application, sometimes it automatically gets redirected to the login page of the IDP.

**Comment by thivi** [comment]
Resolved by https://github.com/asgardeo/asgardeo-auth-react-sdk/pull/53/
