### ISSUE TITLE
Issue while using FormData in httpRequest method

### ISSUE THREAD

**Issue by vlgunarathne** [asgardeo/asgardeo-auth-react-sdk#62]
**Describe the issue:**

An error gets thrown when we try to use the `FormData()` object to attach the data in Form Data format to a PUT request in the httpRequest method.

**How to reproduce:**

Asgardeo React SDK version : `"@asgardeo/auth-react": "^0.2.6",`

Sample code:
```typescript
  const { httpRequest } = useAuthContext();
  const formData = new FormData();
  formData.append('name', 'john');
  httpRequest({
    url: 'https://red-dream-592.getsandbox.com:443/putuser',
    method: 'PUT',
    data: formData,
  })
    .then((response) => {
      console.log({ response });
    })
    .catch((err) => {
      console.log({ err });
    });
```

Error:
```
err: DOMException: Failed to execute 'postMessage' on 'Worker': FormData object could not be cloned. at d (https://localhost:3000/static/js/vendors~main.chunk.js:7962:28) at Object.httpRequest (https://localhost:3000/static/js/vendors~main.chunk.js:8033:37) at _l.<anonymous> (https://localhost:3000/static/js/vendors~main.chunk.js:8367:107) at Generator.next (<anonymous>) at o (https://localhost:3000/static/js/vendors~main.chunk.js:2426:19)
code: 25
message: "Failed to execute 'postMessage' on 'Worker': FormData object could not be cloned."
name: "DataCloneError"
```

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Hareendran7** [comment]
This particular backend REST API only accepts content type of `multipart/form-data`. So from the application we will need to send `FormData` object as the payload. 

@thivi Appreciate if you could consider supporting this requirement in the SDK level
