### ISSUE TITLE
Getting `TextEcoder is not defined` error for NextJs multi-page Application

### ISSUE THREAD

**Issue by suganyasuven** [asgardeo/asgardeo-auth-react-sdk#69]
**Describe the issue:**
I have been trying to integrate the Asgardeo for NextJs multi-page application.  It compiled without any errors. Getting the following error when loading the application.

`TextEcoder is not defined`

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
`asgardeo-auth-react-sdk` was supposed to use with SPAs. Hence, certain operations would need the code to be run on the browser.

As far as i see, you might have to use the `https://github.com/asgardeo/asgardeo-auth-js-sdk` and create a util to access the SDK functions. There you can check if the code is running on the browser and only then run the SDK code.

**ex: utils/asgardeo.js**
```js
import { AsgardeoAuthClient } from "@asgardeo/auth-js";

const store = <read this https://github.com/asgardeo/asgardeo-auth-js-sdk#arguments>;

const auth = new AsgardeoAuthClient(store);

const isBrowser = typeof window !== "undefined"

const auth = isBrowser
    ? auth.initialize({
        signInRedirectURL: "http://localhost:3000/sign-in",
        signOutRedirectURL: "http://localhost:3000/dashboard",
        clientID: "client ID",
        serverOrigin: "https://api.asgardeo.io/t/<org_name>"
    })
    : {}
    
export const isAuthenticated = () => {

    if (!isBrowser) {
        return;
    }

    await auth.isAuthenticated();
}

export const getAuthCode = () => {

    if (!isBrowser) {
        return
    }

    auth.getAuthorizationURL(config).then((url)=>{
        window.location.href = url;
    })
    .catch((error)=>{
        console.error(error);
    });
}

export const getToken = (authorizationCode, sessionState) => {

    if (!isBrowser) {
        return
    }

    auth.requestAccessToken(authorizationCode, sessionState)
        .then((response) => {
            return response;
    })
    .catch((error) => {
        console.error(error);
    });
}

```

**ex: login.jsx**
```jsx
import React from "react"
import { getToken } from "@utils/asgardeo.js"

const LoginPage = () => {

  useEffect(() => {
       getToken
           .then((response) => {
               // handle reponse
           })
           .catch((error) => {
               // handle error
           });
  }, [ // watch for auth code and session state params ]);

  return <div>Authenticating. Please wait...</div>
}

export default LoginPage;
```

**ex: pages/home.js**
```
import React from "react"
import { isAuthenticated,  getAuthCode } from "@utils/asgardeo.js"

const HomePage = () => {

    if (!isAuthenticated()) {
        getAuthCode();
        return <p>Redirecting to login page...</p>
    }

    return (
        <Router>
            <Home path="/home/">
        </Router>
    )
}

export default HomePage;
```

**Comment by suganyasuven** [comment]
> `asgardeo-auth-react-sdk` was supposed to use with SPAs. Hence, certain operations would need the code to be run on the browser.
> 
> As far as i see, you might have to use the `https://github.com/asgardeo/asgardeo-auth-js-sdk` and create a util to access the SDK functions. There you can check if the code is running on the browser and only then run the SDK code then.
> 
> @suganyasuven Could you try out the following and see if it works.
> 
> ### NOTE: Untested Code
> **ex: utils/asgardeo.js**
> 
> ```js
> import { AsgardeoAuthClient } from "@asgardeo/auth-js";
> 
> const store = <read this https://github.com/asgardeo/asgardeo-auth-js-sdk#arguments>;
> 
> const auth = new AsgardeoAuthClient(store);
> 
> const isBrowser = typeof window !== "undefined"
> 
> const auth = isBrowser
>     ? auth.initialize({
>         signInRedirectURL: "http://localhost:3000/sign-in",
>         signOutRedirectURL: "http://localhost:3000/dashboard",
>         clientID: "client ID",
>         serverOrigin: "https://api.asgardeo.io/t/<org_name>"
>     })
>     : {}
>     
> export const isAuthenticated = () => {
> 
>     if (!isBrowser) {
>         return;
>     }
> 
>     await auth.isAuthenticated();
> }
> 
> export const getAuthCode = () => {
> 
>     if (!isBrowser) {
>         return
>     }
> 
>     auth.getAuthorizationURL(config).then((url)=>{
>         window.location.href = url;
>     })
>     .catch((error)=>{
>         console.error(error);
>     });
> }
> 
> export const getToken = (authorizationCode, sessionState) => {
> 
>     if (!isBrowser) {
>         return
>     }
> 
>     auth.requestAccessToken(authorizationCode, sessionState)
>         .then((response) => {
>             return response;
>     })
>     .catch((error) => {
>         console.error(error);
>     });
> }
> ```
> 
> **ex: login.jsx**
> 
> ```js
> import React from "react"
> import { getToken } from "@utils/asgardeo.js"
> 
> const LoginPage = () => {
> 
>   useEffect(() => {
>        getToken
>            .then((response) => {
>                // handle reponse
>            })
>            .catch((error) => {
>                // handle error
>            });
>   }, [ // watch for auth code and session state params ]);
> 
>   return <div>Authenticating. Please wait...</div>
> }
> 
> export default LoginPage;
> ```
> 
> **ex: pages/home.js**
> 
> ```js
> import React from "react"
> import { isAuthenticated,  getAuthCode } from "@utils/asgardeo.js"
> 
> const HomePage = () => {
> 
>     if (!isAuthenticated()) {
>         getAuthCode();
>         return <p>Redirecting to login page...</p>
>     }
> 
>     return (
>         <Router>
>             <Home path="/home/">
>         </Router>
>     )
> }
> 
> export default HomePage;
> ```

Getting the same issue.

**Comment by nipuna777** [comment]
Example of where this fails
https://github.com/LSFLK/MedicinesforLK/runs/7485585913?check_suite_focus=true

```
import { AsgardeoSPAClient } from "@asgardeo/auth-spa";
```

This import is throwing the error for us.

**Comment by pavinduLakshan** [comment]
> Bumping this issue. We are running into a similar issue with the error `Crypto is undefined`. This throws when trying to run jest tests.
> 
> Is there a workaround for this? Thanks!

Hi Nipuna,

Are you still experiencing the error mentioned? If so, please feel free to open a new issue with additional details. This will help us investigate and address the problem effectively.

Closing the current issue for now as OP seems to have got the problem solved.
