### ISSUE TITLE
Exchanged token not getting refreshed during token refresh in requestCustomGrant

### ISSUE THREAD

**Issue by vlgunarathne** [asgardeo/asgardeo-auth-react-sdk#70]
**Describe the issue:**
When an application is using a custom grant to do a token exchange, the first token is obtained from a particular IDP and then it is exchanged for another token from another IDP using a token service. 

As of now, the SDK initiates a refresh token call whenever a 401 response is received to a network call and gets a new token from the first IDP. 
The issue is that although the token from the first IDP is obtained from the refresh token grant, the token exchange with the second IDP doesn't happen  and hence, the access token stored in the worker is the token from the first IDP and all other network calls to the backend REST APIs fail since they are expecting a new token from the second IDP.

**How to reproduce:**

**Expected behavior:**
When the SDK refreshes a token, it would be expected to see if a custom grant has been configured and if so, initiates the custom grant as well.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by tmkasun** [comment]
@thivi This is already fixed in SDK so I think we can close the issue now ?

**Comment by pavinduLakshan** [comment]
Closing based on https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/70#issuecomment-1285840878
