### ISSUE TITLE
Carrot sign (^) is not allowed for passwords

### ISSUE THREAD

**Issue by viradhanus** [asgardeo/asgardeo-auth-react-sdk#80]
If we try to sign up for Asgardeo using **Email** and then try to enter a password which includes **^**, it redirects to the page shown below.
<img width="931" alt="404" src="https://user-images.githubusercontent.com/59219626/152654501-3f1e6f03-cbba-41cd-9174-45ad15eeb991.PNG">

Here according to the given instruction, ^ is considered a valid symbol.
<img width="323" alt="signUP" src="https://user-images.githubusercontent.com/59219626/152654700-e16d7d24-16eb-49e5-87c9-2296f3415e8f.PNG">

After that, if we try to add a new customer, and choose to set a temporary password for the user (2nd method) then also we are not allowed to use ^. But here the validation message(prompt) is correct. (it does not include ^ as a special character)
<img width="567" alt="errorDescribed" src="https://user-images.githubusercontent.com/59219626/152655034-4126c158-5c0b-4ba5-b30c-42b7338cab30.PNG">

If we try the first method to add a new customer ( invite the user to set their own password) the issue remains the same.
<img width="328" alt="misLeading" src="https://user-images.githubusercontent.com/59219626/152655193-3389160f-f9cf-4b9d-857a-32ab5b0ae713.PNG">

Furthermore, when we enter a password that includes ^, it does not fail any test cases initially. 
<img width="307" alt="tryPswWith^" src="https://user-images.githubusercontent.com/59219626/152655348-b83eef97-16a9-4195-a6b9-dadfd50fb53a.PNG">

I observed this behaviour for different OS s (Windows & Linux) as well. Hence, we can resolve this issue by allowing the Carrot sign (^) as a valid symbol.

**Comment by sumedhe** [comment]
According to the screenshots it seems like you are trying with the passwords less than 8 characters. Try with a password which covers all the requirements with the caret symbol and let me know if the issue still exists.

**Comment by pavinduLakshan** [comment]
Closing the issue as this is now fixed. Can you please try the flow again and confirm? 
Please feel free to reopen if you continue to face this issue by any chance.
